### ISSUE TITLE
Broken tests in master

### ISSUE THREAD

**Issue by Spetastian** [Kodkollektivet/owtf-valhalla-client#9]
In commit  3410ca447bd4cec478a22a01f387fe863344f74c
Travis CI output:  
18 passing (88ms)
  2 failing

  1) api-container-mapper.js #mapSingle should map fields of a Core API container entity:
     AssertionError: image_id should be mapped to image.id: expected 'test-image-01' to equal 'i1'
      at Context.<anonymous> (test-api-container-mapper.js:16:20)

  2) api-container-mapper.js #mapMany should map fields of several Core API container entities in an Array:
     AssertionError: first entity's image_id should be mapped to image.id: expected 'test-image-01' to equal 'i1'
      at Context.<anonymous> (test-api-container-mapper.js:35:20)

**Comment by Spetastian** [comment]
Fixed with #10
